POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVkNDAyNzBjMDJmYjRiMzNiMTY5NTk5YyIsImlhdCI6MTU2NDUwMDkwMn0.XqYDmem3PpP8EiklT8PP14RHW7XheBOD10AbO6RqLTE

{
    "title": "test title 5",
    "author": "test author 5",
    "url": "testurl4.com",
    "likes": 5
}